{
 "title": "Health Tracking",
 "time": { "from": "now-15d", "to": "now" },
 "panels": [
  {
   "title": "Calories burned",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "totalCaloriesBurned",
     "select": [
      [
       { "params": [ "energy_inCalories" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "app::tag", "operator": "=", "value": "com.kieslect.ksos" }
     ]
    }
   ]
  },
  {
   "title": "Distance (Km)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "distance",
     "select": [
      [
       { "params": [ "distance_inKilometers" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "app::tag", "operator": "=", "value": "com.kieslect.ksos" }
     ]
    }
   ]
  },
  {
   "title": "Steps count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "steps",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "app::tag",
       "operator": "=",
       "value": "com.google.android.apps.fitness"
      }
     ]
    }
   ]
  },
  {
   "title": "Weigh (Kg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "measurement": "weight",
     "select": [
      [
       { "params": [ "weight_inKilograms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "app::tag", "operator": "=", "value": "cn.fitdays.fitdays" }
     ]
    }
   ]
  },
  {
   "title": "Body Fat Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "bodyFat",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  }
 ]
}