services:
  influxdb2:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: Abc@13579
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: admin-token
      DOCKER_INFLUXDB_INIT_ORG: oliver
      DOCKER_INFLUXDB_INIT_BUCKET: health-connect
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  influxdb2-data:
  influxdb2-config:
  grafana-storage:
